Add RES linker
pypsa-meets-africa/pypsa-earth-sec pull request #136
Opened 2022-08-26 14:26 UTC by Hazem-IEG

# Closes # (if applicable).

## Changes proposed in this Pull Request

## Checklist

- [x] I tested my contribution locally and it seems to work fine.
- [ ] Code and workflow changes are sufficiently documented.
- [x] Newly introduced dependencies are added to `envs/environment.yaml` and `envs/environment.docs.yaml`.
- [x] Changes in configuration options are added in all of `config.default.yaml`, `config.tutorial.yaml`, and `test/config.test1.yaml`.

2022-08-29 13:09 UTC, energyLS commented
@Hazem-IEG There is one merge conflict, can you have a look at that? After this is solved the CI will run and tell us wether it is fine to merge, and I will be happy to review it :)

2022-08-31 13:29 UTC, energyLS commented
> @Hazem-IEG There is one merge conflict, can you have a look at that? After this is solved the CI will run and tell us wether it is fine to merge, and I will be happy to review it :)

I have solved the merge conflict (don't worry: that was done quickly). Now waiting for the CI to pass to review the code

2022-08-31 13:44 UTC, energyLS requested changes
Nice implementation. If the proposed changes are implemented, the CI should work and we can merge it

2022-08-31 13:44 UTC, energyLS commented on Snakefile
> +        + "/logs/elec_s{simpl}_{clusters}_ec_l{ll}_{opts}_{sopts}_{planning_horizons}_{discountrate}_updated_memory.log",
Why is the string "updated" added and is this a permanent solution?

2022-08-31 13:44 UTC, energyLS commented on config.yaml
> +custom_data:
Please add all changes in this file also to `https://github.com/pypsa-meets-africa/pypsa-earth-sec/blob/main/test/config.test1.yaml`

2022-08-31 13:44 UTC, energyLS commented on config.yaml
> +custom_data:
Otherwise the CI fails

2022-09-03 16:16 UTC, Hazem-IEG commented
CI fixed @energyLS ;)

2022-09-08 10:10 UTC, davide-f commented
My feeling is that discountrate is interpreted as a string by snakemake, but we need it as a float in the execution.
I'd make sure to perform the appropriate parsing. I add a review on that in about 1-2 hours

2022-09-13 07:58 UTC, Hazem-IEG commented
I finally fixed the error, it is a problem with Biomass that I still didn't figure out yet.  Could you please check the error as you worked more on this carrier? @energyLS

2022-09-13 09:30 UTC, energyLS commented
> I finally fixed the error, it is a problem with Biomass that I still didn't figure out yet. Could you please check the error as you worked more on this carrier? @energyLS

Interesting. Yes I will take care

2022-09-14 12:53 UTC, Hazem-IEG commented
This should be ready now. Maybe we need to open a new branch for the biomass issue. @energyLS

2022-09-14 12:55 UTC, energyLS approved these changes

2022-09-14 13:00 UTC, energyLS commented
> This should be ready now. Maybe we need to open a new branch for the biomass issue. @energyLS

Yes, this PR is now ready. I have opened up a new issue for the biomass issue in #140.
Thanks for the contribution.

2022-09-14 13:00 UTC, merged